version: '3.8'

services:
  eth-deposit-tracker:
    build: .
    container_name: eth-deposit-tracker
    restart: always
    environment:
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo
    ports:
      - "8000:8000"  # Exposing Prometheus metrics port
    networks:
      - tracker-network

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"  # Exposing MongoDB port
    volumes:
      - mongo-data:/data/db
    networks:
      - tracker-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - tracker-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - tracker-network
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Set the default admin password
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel

networks:
  tracker-network:

volumes:
  mongo-data:
